### PR TITLE
Revert "Support for Debian family systems"

### PR DESCRIPTION
**Pull request by martbhell**
Reverts CSCfi/ansible-role-puppetize#17

### CODE REVIEW

**Comment by martbhell** [comment]
@goetzk actually this is a bit problematic for us as we run this role frequently with "gather_facts: False". Can you think of a way to do this different OS bit based on something else than something in facts?

**Comment by martbhell** [comment]
Thanks! Got a bit trigger happy there after seeing the external PRs! Should have read the README for how I should test this role manually :)

**Comment by goetzk** [comment]
Hi @martbhell ; I'm not sure what other options might be but I'll see if I can think of something.
If gathering facts isn't an option it may have to be information provided via inventory.

**Comment by martbhell** [comment]
Hmm.. spitballing some other options:

 - A) different tasks with conditionals depending on if we are gathering facts or not
 - B) reimplement the os_family bit with a command+register task or some such
 - C) maybe have a set_fact task or use |default filter with defaults? like:

```
- set_fact
    my_os_family: "{{ ansible_os_family|default('RedHat') }}"

- name: gather os specific variables	
  include_vars: "{{ item }}"	
  with_first_found:	
    - "vars/{{ my_os_family }}.yml"
```

But this last bit makes the factless runs only available for RedHat based distros which works for us but it's not so nice for others..

- D) Maybe also something like this could work (haven't tested syntaxes..):

add puppetize_fallback_os: "RedHat" to defaults/main.yml

```
- name: gather os specific variables	
  include_vars: "{{ item }}"	
  with_first_found:	
    - "vars/{{ ansible_os_family|default(puppetize_fallback_os) }}.yml"
```

That could also make this work for Debian, one would just have to update a variable which isn't too bad I suppose..

**Comment by goetzk** [comment]
As a top level split something which can be determined via facts for debian and redhat is using the version files they provide.

/etc/debian_version -> debian family
/etc/redhat-release -> redhat family

Checking for those files will one or two new tasks to the role but shouldn't be too burdensome overall.
Would you be interested in a PR using this approach?

**Comment by goetzk** [comment]
The change looks something like this (I haven't tested yet so it might need to change) but matches the puppet configuration idiom used further down the task list.
```
diff --git a/tasks/main.yml b/tasks/main.yml
index 45ae8a2..f535592 100644
--- a/tasks/main.yml
+++ b/tasks/main.yml
@@ -1,9 +1,19 @@
 ---
 
+- name: check for Debian family system
+       stat:
+               path: '/etc/debian_version'
+       register: reg_puppetize_os_debian
+
+- name: set os family fact
+       set_fact:
+               os_family: 'Debian'
+       when: reg_puppetize_os_debian.stat.exists == True
+
 - name: gather os specific variables
   include_vars: "{{ item }}"
   with_first_found:
-    - "vars/{{ ansible_facts['os_family'] }}.yml"
+    - "vars/{{ os_family |default('RedHat')}}.yml"
 
 - name: install puppetlabs repo
   yum:

```

**Comment by junousi** [comment]
> The change looks something like this (I haven't tested yet so it might need to change) but matches the puppet configuration idiom used further down the task list.

Looks good, especially since not reading too much into the file contents (afair it's a bit different for e.g. sid than stable versions). I have a feeling there still might be some gotcha somewhere but in any case happy to look at the PR if you open one.

**Pull request merged**
